### ISSUE TITLE
[Milestone] Bindings (Rust, NodeJS, Golang)

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#121]
**Milestone**: https://github.com/waku-org/pm/milestone/10

Provide functioning bindings over nwaku in the following environments, ordered by priority:

- Rust (swap go-waku with nwaku)
- NodeJS
- Golang

# Functionality

Bindings should provide the following functionality
- DiscV5 + DNS Discovery 
- RLN Relay and relay
- auto sharding and static sharding
- Store client (lower priority)

And, the "C" binding should be documented in each of the above features. That means that we should have a clear example, or test, on how to use such feature taking this simple C example as a reference: https://github.com/waku-org/nwaku/blob/master/examples/cbindings/waku_example.c

Once these 3 bindings are shipped we can consider this Milestone complete.

Further functionality can be scoped further down the road.

Further functionalities:
- Light client
- Service node
- Encryption v1 and v2

# Epics
- [ ] nwaku: https://github.com/waku-org/pm/issues/141
- [ ] QA: 
- [ ] Docs:
- [ ] Eco-Dev:

**Comment by vpavlin** [comment]
> * Rust (swap go-waku with nwaku)

This will not (IMO) be possible with the listed functionality - The Graph uses light clients through Rust bindings

**Comment by chair28980** [comment]
go-waku issue handling Rust bindings: https://github.com/waku-org/waku-rust-bindings/issues/53

**Comment by axiomatic-aardvark** [comment]
> This will not (IMO) be possible with the listed functionality - The Graph uses light clients through Rust bindings
Petko from GraphOps here (core dev at The Graph), we are totally OK with deprecating filter protocol moving forward, we use relay by default for everything

**Comment by fryorcraken** [comment]
Note that while the bindings, and any Waku library in general, should default to using RLN Relay + autosharding (ie, waku network)
We should at least make relay (no rln) and static sharding available to enable projects to use their own network.

**Comment by richard-ramos** [comment]
@Ivansete-status and I discussed today the approach for rust bindings, and we will reuse the waku-rust-bindings repository like this:
- `master` branch will continue to be using go-waku, doing patch versions for bug fixes,
- A separate branch will be created for integration with nim. 
- Once we deliver the features described in this issue we'll reset `master` branch to point to last commit of nwaku integration branch, and publish a new version of the rust crate

**Comment by Ivansete-status** [comment]
I think the Epics are getting clearer now. The only one that I don't know how to complete for now is the Golang one.
@richard-ramos may kindly edit this milestone description so that we have a clearer Golang epic? I think the tasks there should be to migrate go-waku to nwaku from the _Status_ perspective.

**Comment by richard-ramos** [comment]
done!

**Comment by fryorcraken** [comment]
LGTM for sign-off. will be discussed at Waku PM call today.

**Comment by chair28980** [comment]
nwaku Epic here: https://github.com/waku-org/nwaku/issues/2420

Tasks listed in MIlestone description have been moved to the Epic's description for further breakdown.

**Comment by chair28980** [comment]
Signed off during EU-NA PM 2024-02-19.

**Comment by fryorcraken** [comment]
Descoped. Cc @chair28980

**Comment by chair28980** [comment]
Closing per above comment, placeholder for above mentioned Deliverable: https://github.com/waku-org/pm/issues/203
