### ISSUE TITLE
[Deliverable] Metric: Count store messages

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#167]
Project: https://github.com/orgs/waku-org/projects/22/views/1

## Description

[Message-finder](https://github.com/waku-org/message-finder) is used to compare the number of Status messages across Status nodes to understand the potential discrepancies and odd behaviour of messages being inserted in the past in a given channel.

This deliverable captures the message count on all Waku fleets to use as a metrics of the efficacy of store sync.

Tool is being created in https://github.com/waku-org/storenode-messages repo, work on other clients is not expected.

## Tasks

- [x] https://github.com/waku-org/storenode-messages-counter/issues/8

**Comment by chair28980** [comment]
https://github.com/waku-org/storenode-messages/issues/8

**Comment by chair28980** [comment]
Closing as completed https://github.com/waku-org/storenode-messages-counter/issues/8#issuecomment-2150845757

**Comment by fryorcraken** [comment]
Re-opened because we need some graph or dashboard to actually see the missing message count, so that we can check that with store sync there are indeed no recent message missing.

There was also performance issue due to the traffic spike.

@richard-ramos  Are performance improvement done? When do you think we can have the graphs?

**Comment by richard-ramos** [comment]
Graphs can be seen here: https://grafana.infra.status.im/d/hmX6pJ_Iz/storenode-message-counter?orgId=1 

![image](https://github.com/user-attachments/assets/54e7be2b-6f1e-4003-859b-157310a8d50a)

**Comment by richard-ramos** [comment]
I did add some degree of concurrency to try improve the performance. So far the delay to process the messages seem to hover around ~8m which seems fine

**Comment by fryorcraken** [comment]
Latest update on this. The current diagram are good to highlight issues with the store node. However, it does not enable us to confirm whether store sync are able to fix missing messages. The proposal is to add a secondary check that reviews if known missing messages are still missing after some times. Here is the description of the graphs:

3 graphs per period:

- past hour
- past day
- past week

for each

- x axis is time of recheck
- number of *still* missing messages within the period of the graph (per store node)

So if you look at past hour, it shows at time `t` (time of recheck), what messages where still missing within `t - 1h` to `~t` or most likely`t - 2 min`

So ideally, from the moment store sync is enabled, past day and past week always flat line.

And past hour can be used to debug store sync and improve it to flat line it.

And this way, we can also affirm that the store are sync'd over given period of time.


@SionoiS @Ivansete-status if you can confirm that such change would help confirm that store sync is able to recover store node message discrepancies that would be great.

Also please clarify:
- how often does/will store sync run?
- what period of time does store sync covers (how much in the past it tries to sync messages)

on Status fleets.

**Comment by fryorcraken** [comment]
Also, @richard-ramos, can we also deploy it for TWN? Would be good to have if projects complain of message loss. not urgent.

**Comment by SionoiS** [comment]
> * how often does/will store sync run?

Every hours.

> * what period of time does store sync covers (how much in the past it tries to sync messages)

Last hour minus 20s

**Comment by Ivansete-status** [comment]
@fryorcraken 
> @SionoiS @Ivansete-status if you can confirm that such change would help confirm that store sync is able to recover store node message discrepancies that would be great.

I think this is a great idea but we can make it simpler, i.e., make the `storenodes-messages` tool to keep track of the number of seen messages on each storenode, and then just represent the relative difference amongst them. wdyt @richard-ramos ?

**Comment by richard-ramos** [comment]
Hm. I did add the message re-verification requested by Franck earlier and did not add much complexity to the code. I think it should be fine since it is extra information that might be useful. If later we see that it is not really needed, we can drop the changes (I'm all in for removing code! :) )

**Comment by fryorcraken** [comment]
All features done and added to dashboard: https://grafana.infra.status.im/d/hmX6pJ_Iz/storenode-message-counter?orgId=1&from=now-7d&to=now

Dogfooding started. Will review in a week and close deliverable.

**Comment by fryorcraken** [comment]
Done!
