### ISSUE TITLE
[Deliverable] Review connection management strategy & back-off & long disconnection issues

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#177]
## Epics

- [ ] https://github.com/waku-org/pm/issues/210

**Comment by fryorcraken** [comment]
This deliverable seems to be well progressed.
I suggest an increase of scope to include the peer discovery work in it.
Scoping may need review as Waku Research is now involved..

What is the current status and do we have some ETA?
@plopezlpz @chaitanyaprem @jm-clius

**Comment by jm-clius** [comment]
I've been considering the peer discovery improvements as part of https://github.com/waku-org/pm/issues/213
Work is progressing: first step is to add measurements to understand how well discovery is currently behaving. This is almost done. The next step is to try various ways of tuning discv5 to see if we can improve the situation for Status specifically. After that we'll consider adding more discovery methods, e.g. rendezvous. ETA would be roughly three months.

**Comment by fryorcraken** [comment]
> I've been considering the peer discovery improvements as part of #213 Work is progressing: first step is to add measurements to understand how well discovery is currently behaving. This is almost done. The next step is to try various ways of tuning discv5 to see if we can improve the situation for Status specifically. After that we'll consider adding more discovery methods, e.g. rendezvous. ETA would be roughly three months.

Fair enough. There was a feeling of urgency at first on discv5 but I believe it is now mitigated by also using peer exchange.

If peer discovery is in a fair state at this point in time (cc @chaitanyaprem ) then happy for it to be done as part of #213.

**Comment by chaitanyaprem** [comment]
> > I've been considering the peer discovery improvements as part of #213 Work is progressing: first step is to add measurements to understand how well discovery is currently behaving. This is almost done. The next step is to try various ways of tuning discv5 to see if we can improve the situation for Status specifically. After that we'll consider adding more discovery methods, e.g. rendezvous. ETA would be roughly three months.
> 
> Fair enough. There was a feeling of urgency at first on discv5 but I believe it is now mitigated by also using peer exchange.
> 
> If peer discovery is in a fair state at this point in time (cc @chaitanyaprem ) then happy for it to be done as part of #213.

Yes, we can consider this to be done for now. Any new issues observed can be tracked separately.

Whatever additional peer discovery related work is being done, better to take it separately as @jm-clius mentioned.

**Comment by chaitanyaprem** [comment]
@chair28980 we can mark this as completed.

**Comment by chair28980** [comment]
cc @fryorcraken for completion check
