### ISSUE TITLE
[Deliverable] Tooling: filter and light push protocols

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#178]
## Epics

- [x] https://github.com/waku-org/nwaku/issues/3079
- [ ] js-waku

## Output

**Comment by fryorcraken** [comment]
@NagyZoltanPeter @Ivansete-status where is the dashboard we talked about please?

**Comment by NagyZoltanPeter** [comment]
> [@NagyZoltanPeter](https://github.com/NagyZoltanPeter) [@Ivansete-status](https://github.com/Ivansete-status) where is the dashboard we talked about please?

@fryorcraken , @Ivansete-status: All development and refinement is done, it is currently under work for deployment to infra-misc.
I'm just creating necessary jenkins jobs and infra pr for it.

**Comment by NagyZoltanPeter** [comment]
lite-protocol-tester is now capable to:

- Run on any fleet. Using PeerEx-capable bootstrap nodes, it can test available service nodes and change service nodes during tests in case a certain amount of failure occurs. 
- liteprotocoltester is [published as docker image](https://harbor.status.im/harbor/projects/9/repositories/liteprotocoltester/artifacts-tab).
- It can be configured and run easily with help [lpt-runner repository.](https://github.com/waku-org/lpt-runner) 
- It is deployed to infra-misc appliance and runs a short test on status.prod network in every 3h periodically.
- Dashboards are available in every cases. Either running with lpt-runner (-> localhost:3033) 
or running at infra (-> https://grafana.infra.status.im/d/fdw6pgh9odszkd/lite-protocol-test-on-status-prod?orgId=1&from=now-7h&to=now)
