### ISSUE TITLE
[Deliverable] Review MVDS usage and fail path

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#189]
Project board: https://github.com/orgs/waku-org/projects/33/views/1

Review MVDS usage for direct messages and ensure that the fail path is handled correctly with either feedback on the UI or automated retries.

MVDS protocol is already in use for some direct messages. Ensure it is the case for contact requests, join requests, 1:1 chat and private groups.

Also review the fail path for MVDS (are messages retried later or is there feedback/retry on the UI)?

The output of this is likely to include GUI change recommendations to add retry buttons or just simply retry indefinitely (for contact requests etc) in addition to some logic change (e.g. ensure the retry happens after reconnection).

## Epics

- [x] https://github.com/waku-org/pm/issues/215

**Comment by kaichaosun** [comment]
Close it as no more work needs to be done.
