### ISSUE TITLE
[Deliverable] RLNv2 in nwaku

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#204]
Project board: https://github.com/orgs/waku-org/projects/46/views/1

## Epics

- [x] https://github.com/waku-org/pm/issues/216
- [x] https://github.com/waku-org/pm/issues/168

**Comment by alrevuelta** [comment]
Unsure deliverable vs milestone, but is this a duplicated of
https://github.com/waku-org/pm/issues/168 ?

**Comment by chair28980** [comment]
> Unsure deliverable vs milestone, but is this a duplicated of #168 ?

Yes indeed, thank you, I will fix.
