### ISSUE TITLE
[Deliverable] Maturing RLN variables/parameters revision 

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#205]
Project board: https://github.com/orgs/waku-org/projects/47/views/1

## Epics

- [ ] https://github.com/waku-org/pm/issues/223
- [ ] https://github.com/waku-org/pm/issues/224

**Comment by jm-clius** [comment]
@fryorcraken can we rename this deliverable to "Specify RLN smart contract for mainnet"?

That would mean we can close this as soon as the RFC arising from https://www.notion.so/Minimal-specification-for-RLN-on-mainnet-fba4417b0eb84bf887969a78f7f625d5 is published and presented to Status. There would also be no `nwaku` epic anymore.

The description of the deliverable in the roadmap would remain the same, except that the discussion is centered around an RFC with clearer DoD than a vague "maturing variables".

**Comment by fryorcraken** [comment]
> @fryorcraken can we rename this deliverable to "Specify RLN smart contract for mainnet"?
> 
> That would mean we can close this as soon as the RFC arising from [notion.so/Minimal-specification-for-RLN-on-mainnet-fba4417b0eb84bf887969a78f7f625d5](https://www.notion.so/Minimal-specification-for-RLN-on-mainnet-fba4417b0eb84bf887969a78f7f625d5) is published and presented to Status. There would also be no `nwaku` epic anymore.
> 
> The description of the deliverable in the roadmap would remain the same, except that the discussion is centered around an RFC with clearer DoD than a vague "maturing variables".

As discussed, the output of this deliverable is a roadmap + a decision on the RLN parameters.

Once we have the raw RFC for RLN economical parameters + new deliverables to describe the work needed to get to mainnet then we can close this present deliverable and mark it as done.

**Comment by jm-clius** [comment]
Specification published for RLN contract, detailing membership mechanism and selected parameters: https://github.com/waku-org/specs/blob/master/standards/core/rln-contract.md
