### ISSUE TITLE
[Epic: nwaku] RLNv2 in nwaku

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#216]
## Tasks

- [x] https://github.com/waku-org/nwaku/issues/2345

**Comment by jm-clius** [comment]
@chair28980 even though there are some issues open related to bugs or maintenance chores for RLN:
https://github.com/waku-org/nwaku/issues/2928
https://github.com/waku-org/nwaku/issues/2924
I'd suggest closing this epic as completed. We should expect some maintenance tasks to appear from time to time, but I think it's better not to keep epics/deliverables open indefinitely if the main goal has been achieved.
