### ISSUE TITLE
[Epic: QA] Store v3-beta - Message Hashes

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#225]
### Gather information
- Read RFC
- Check data on Status fleet grafana and kibana
- workshop/discuss use cases and testing approach

### Write Test plan
- use the gathered information to define a test plan
- ask for reviews of test plan
- finalise test plan

### Get test tools
- assess what tools are available
- implement any additional tools

**Comment by fryorcraken** [comment]
From @fbarbu15
> yes, I added 50+ tests and reported several issues that are all fixed. I think we have good coverage
