### ISSUE TITLE
[Milestone] Execute an array of community growth activity

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#36]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Milestone label**: `E:2023-eco-growth`
**Priority Tracks**: Growth
**Due date**: 30 Nov 2023

# Summary

Execute an array of community growth activity, at a minimum:
- Prizes at hackathons (targeting 8)
- Talks, Workshops and side events
- Bounties published and delivered

# Justification

Waku is a public good infrastructure that harness the developer, platform, contributor and operator community to strengthen its USP: privacy-preserving, censorship-resistant, surveillance-prone and portable.
To be successful and sustainable, Waku needs a strong community.

# Milestones

## Eco Dev
 
- [ ] Milestone title or link
...

## Research

- [ ] Milestone title or link

**Comment by chair28980** [comment]
Close once all eco dev materials are in Notion

**Comment by fryorcraken** [comment]
@chair28980 can we close?

**Comment by chair28980** [comment]
@fryorcraken good to close, synced with @hackyguru and we are aligned on near-term community growth items we are tracking. Tracking EcoDev pipeline items previously tracked in internal-waku-outreach repo here: https://www.notion.so/d774f45add104d3ba823b7eb6f248fff?v=45764726312f43e08bc5cb18061592d2
