### ISSUE TITLE
[Milestone] Dogfooding of RLN by platforms has started

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#37]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Milestone label**: `E:2023-rln`
**Priority Tracks**: Generating Revenue (Sustainability & Longevity)
**Due date**: 30 Nov 2023

# Summary

- Delivery of Dev Rel asset such as documentation (high level and code), examples
- Discussion with platforms (Status, and external) about usage of RLN
- Push of RLN to developer community via bounties and hackathon prizes

# Justification

As part of the Logos strategy, Waku needs to generate revenue and have a clear road map to sustainability.
To be widely adopted, Waku needs to gain social confidence that it will remain. Platforms must trust the Waku network and development effort have a sustainable model. For the Waku network to be sustainable, operators must trust the incentivization model is sound.

RLN is currently a key asset to the project sustainability roadmap

# Milestones

## Eco Dev
 
- [ ] Milestone title or link
...

## Research

- [ ] Milestone title or link

**Comment by fryorcraken** [comment]
**monthly update **

Local simulation of the effect of RLN on Waku Relay network has raised a number of bugs now fixed and integrated in both nwaku and go-waku. Next step will be to deploy a contract with 10,000 membership to continue testing.

**Comment by jm-clius** [comment]
Closing milestone. Replaced by epic: https://github.com/waku-org/pm/issues/70
