### ISSUE TITLE
[Milestone] First protocol to incentivize operators has been defined

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#38]
2023 Milestones: https://notes.status.im/s/iylE6wdli#

**Milestone label**: `E:2023-incentize-operators`
**Priority Tracks**: Generating Revenue (Sustainability & Longevity)
**Due date**: 31 Dec 2023

# Summary

- First protocol to incentivize operators has been defined and rolled out on testnet
- RFC defining how node operators can be incentivized to run Waku node has been defined

Note: strong dependency on the Logos Tokenomics team.

# Justification

As part of the Logos strategy, Waku needs to generate revenue and have a clear road map to sustainability.
To be widely adopted, Waku needs to gain social confidence that it will remain. Platforms must trust the Waku network and development effort have a sustainable model. For the Waku network to be sustainable, operators must trust the incentivization model is sound.

# Milestones

## Eco Dev
 
- [ ] Milestone title or link
...

## Research

- [ ] Milestone title or link

**Comment by fryorcraken** [comment]
**monthly update**

This milestone is planned to be started later this year (November). However, some further reasoning around incentivization has been [drafted](https://github.com/waku-org/research/issues/10).

**Comment by alrevuelta** [comment]
**monthly update**

A new hire will be working on prototyping crypto incentives for light clients, idea drafted [here](https://github.com/waku-org/research/issues/21)

**Comment by jm-clius** [comment]
Closing milestone. Replaced by epic: https://github.com/waku-org/pm/issues/80
