### ISSUE TITLE
Update labeling definitions in labels.yml

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#47]
Dangerous action proceed with caution!

Update label definitions in labels.yml to reflect the new tracking system being adopted across the Logos ecosystem.

### Steps
- create labels in github with M:
- assign labels
- add them to labels.yml and push on master -> label definition will be overridden but assigned label should not mveo
- verify, delete E labels from labels.yml

### Post Update Steps
1. Update labeling
- update labels to reflect the updating naming structure in https://github.com/waku-org/pm/blob/master/.github/labels.yml
- submit pr for review as this is a dangerous action
2. New formatting structure for new Milestones/Epics/Tasks
- new  tracked with correct labeling scheme
- coordinate with Lalo on dashboard views
3. Past work
- When QA of new system is satisfied update past work to reflect new system for seamless tracking (as best as possible)
- lowest priority

**Comment by fryorcraken** [comment]
Hold your horses, see discussions in Discord. Also keen to get  minutes from the chat you had.

**Comment by fryorcraken** [comment]
Thsi is done
