### ISSUE TITLE
Open membership mechanism

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#52]
Mainnet contract (and instructions/guide) where anyone willing to pay the registration transaction fee can register a new membership, with membership limit set upfront. At this stage deployed RLN validators should build memberships off mainnet.

Priority: Critical for launch

**Comment by rymnc** [comment]
Please define the membership limit so that we can alter the contract's upper limit :)

**Comment by chair28980** [comment]
@jm-clius what should the membership limit be set to?

**Comment by jm-clius** [comment]
> Please define the membership limit so that we can alter the contract's upper limit :)

I think we decided on `10000`.

**Comment by fryorcraken** [comment]
Pretty sure we agreed for mainnet later? Should we set a limit on Sepolia contract though? @jm-clius @rymnc

**Comment by jm-clius** [comment]
Yes, this item is no longer critical for launch (we are parking mainnet deployment for a while), but it's probably a good idea to limit the number of memberships on the Sepolia contract @rymnc. Could we do this in a way that is upgradable in case we decide to change the limit (for whichever reason) as the network grows?

**Comment by rymnc** [comment]
> Yes, this item is no longer critical for launch (we are parking mainnet deployment for a while), but it's probably a good idea to limit the number of memberships on the Sepolia contract @rymnc. Could we do this in a way that is upgradable in case we decide to change the limit (for whichever reason) as the network grows?

It already is, I can deploy a new storage with this limit and force transition if you'd like.
