### ISSUE TITLE
Membership for all internal CCs

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#53]
To kickstart dogfooding, a membership mechanism mostly focused on getting internal CCs to start using RLN. This could e.g. provide instructions to internal CCs on how to generate, configure and keep a suitable key for RLN, collect public key material for eligible CCs (and other parties) via a Typeform, register a membership on their behalf in a membership contract and ensure that deployed nodes are aware of this contract. At this stage the membership contract can still be deployed on a testnet, although we may want to migrate these initial members to a "final" mainnet contract once stable.

Priority: Critical for launch

**Comment by rymnc** [comment]
All CC's are empowered to use the [`rln-keystore-generator`](https://github.com/waku-org/nwaku/blob/master/docs/tutorial/rln-keystore-generator.md) to register themselves to the rln membership set.

**Comment by rymnc** [comment]
I cannot close this issue, so please do :)

**Comment by alrevuelta** [comment]
> All CC's are empowered to use the [rln-keystore-generator](https://github.com/waku-org/nwaku/blob/master/docs/tutorial/rln-keystore-generator.md) to register themselves to the rln membership set.

On top of that this bounty could also help https://github.com/waku-org/bounties/issues/9. Same functionality as rln-keystore-generator but via a UI.

**Comment by chair28980** [comment]
> I cannot close this issue, so please do :)

Closing per @rymnc's comment :)
