### ISSUE TITLE
RLN key mechanism and proofs for all publishers

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#54]
Ensuring that on all Waku clients publishers can:

- manage RLN membership(s) and keys
- generate and attach RLN proofs when using any publishing API calls (lightpush, relay, etc.)

Owner: @rymnc (but delegate implementation ownership for different Waku clients)

Priority: Critical for launch

**Comment by rymnc** [comment]
Addressed as a part of https://github.com/waku-org/nwaku/issues/1906 - under which - 
- the `rln_keystore_generator` was added to create and register credentials to the rln membership set: 
  - https://github.com/waku-org/go-waku/pull/654
  - https://github.com/waku-org/nwaku/pull/1925
  - https://github.com/waku-org/nwaku/pull/1928
  - https://github.com/waku-org/nwaku/pull/1931
- and proofs are attached thru api calls (rest + json-rpc):
  - https://github.com/waku-org/nwaku/pull/1968
  - https://github.com/waku-org/nwaku/pull/1852

**Comment by rymnc** [comment]
I cannot close this issue, so please do :)

**Comment by chair28980** [comment]
Closing per @rymnc's comment.
