### ISSUE TITLE
Task: Waku Network raw RFC

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#59]
Single RFC that specifies the Waku Network. Some details that should be included:
- shard allocation (for gen0)
- content topic use; pubsub topic format
- rough overview of generations (and mentioning that this is mostly future work)
- use of Waku protocols and Waku Message, defaults and recommended services
- resource-restricted nodes
- RLN and membership configuration
- autosharding requirements (basic and potential future operation)
- bandwidth limiting mechanisms
- etc.

**Owner**: @jm-clius (with specific sections covered by relevant owners)
**Priority**: Critical for launch

**Comment by fryorcraken** [comment]
Resolved by https://github.com/vacp2p/rfc/pull/616

cc @jm-clius
