### ISSUE TITLE
docs: requirements for being a Waku fleet owner

### ISSUE THREAD

**Issue by jm-clius** [waku-org/pm#61]
This tracks the work necessary to achieve the following:
- documented guidelines on how to set up a Waku fleet (e.g. considering bootstrap trees, separating store nodes from bootstrap nodes, considering static vs autosharding)
- guideline requirements on a fleet owner, i.e. what is necessary to maintain, expand and monitor your fleet(s)?
- specific guidelines for Status Communities on setting up and maintaining their own fleets

**Comment by fryorcraken** [comment]
How do we make this happen? I am guessing this is blocked by dogfooding by Status of static sharding first to ensure we smooth out any issues/bug found? Once a potential period of heavy debugging is behind us then we handover? or do we want to do that beforehand. Some concerted effort is needed for this.

**Comment by jm-clius** [comment]
This should be prioritised, indeed. Let's discuss in next week's 1:1 what is needed to make this happen and to action and finish within the next month.

**Comment by fryorcraken** [comment]
Document produced: https://www.notion.so/Fleet-Ownership-7532aad8896d46599abac3c274189741 and session with stakeholders done.
