### ISSUE TITLE
[Epic] 1.1 Network requirements and task breakdown

### ISSUE THREAD

**Issue by jm-clius** [waku-org/pm#62]
**Epic label**: `E:1.1 Network requirements and task breakdown`

# Summary

This tracks the work necessary to determine the specifications for a public Waku Network, a rough design to achieve this and a breakdown of tasks necessary to get there.

The deliverable of this milestone is twofold:

A) Firstly answer questions such as:

1. How many shards to we want to support initially? Do we know how to increase this in future?
2. What is the reasonable bandwidth expectation per shard?
3. What is a reasonable message rate expectation per shard?
4. What is a reasonable number of publishers per shard?
5. What is a reasonable max message size for the shard?
6. What membership mechanisms and limits should we set and should this be done on a per-shard basis?

B) Breakdown the list of tasks necessary to achieve the design determined in (A) and do initial task assignment to core contributors

# Acceptance Criteria

# Tasks

- https://github.com/vacp2p/rfc/pull/616

**Comment by jm-clius** [comment]
Weekly Update

- _achieved_: Started working on Waku Network RFC. Visibility and traceability in GH improvements.
- _next_: Continue working on Waku Network RFC.

**Comment by jm-clius** [comment]
**Weekly Update**

- _achieved:_ Opened first raw version of Waku Network RFC for review.
- _next:_ Address any feedback on the Waku Network RFC and complete underdefined sections.

**Comment by fryorcraken** [comment]
@jm-clius what is realistic revised date pleaes?

**Comment by jm-clius** [comment]
This can be closed once https://github.com/vacp2p/rfc/pull/616 is merged. Realistically ~22 Sept.

**Comment by jm-clius** [comment]
**Weekly Update**

- _achieved_: Further specifications added for RLN. Merged and published first version of RFC
- _next_: Define first launchable (sub)network for Devconnect.

**Comment by jm-clius** [comment]
This issue is closed by the merging of https://github.com/vacp2p/rfc/pull/616
