### ISSUE TITLE
[Epic] 1.5: Launch and dogfood integrated public Waku Network MVP

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#68]
**Epic label:** `E:1.5: Launch and dogfood integrated WN MVP`

# Summary

  

Combining outputs from all other tracks and epics, launch and dog-food the Waku Network MVP as set out in https://github.com/waku-org/research/issues/1 by the end of the year.

# Tasks

- [x] https://github.com/waku-org/pm/issues/58

**Comment by jm-clius** [comment]
**Weekly Update**

- _achieved_:
   - Launched team-internal CC dogfooding with nwaku nodes and RLN Sepolia contract
   - Introduced landing page and tutorials to join the network and publish using nwaku-compose
- _next_:
    - Soft launch of the network at Devconnect Istanbul
    - Extend dogfooding to other clients (js-waku, go-waku)

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: come up with go-waku-compose to run a go-waku node in order to dogfood the public waku network
- _next_: fix issues in go-waku-compose to support secure websockets and auto-fetch public IP

**Comment by chaitanyaprem** [comment]
**Weekly Update**

- _achieved_: add new metrics and make go-waku-compose dashboard functional, dogfooding the network with go-waku node
- _next_: fix few pending items in dashboard
