### ISSUE TITLE
[Epic] 3.1: DoS requirements and design

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#69]
**Epic label:** `3.1: DoS requirements and design`

# Summary

  

This builds off the general specification phase to answer questions specific to DoS/spam protection in the public Waku Network. The deliverable is answer to questions such as:
1. What is a reasonable epoch size and rate design for the network? Should this be managed per shard or for the entire autosharded network?
2. What is a good initial, test membership mechanism and what is the roadmap to onboard more members?
3. Should we allow a certain amount of "free" traffic (without membership/proofs) on the network? How is this fairly managed and limited?

# Acceptance Criteria

# Tasks

- [ ] https://github.com/vacp2p/rfc/pull/616

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
@jm-clius @alrevuelta I believe this is not yet fully done. What is a realistic revised date? Cc @chair28980

**Comment by alrevuelta** [comment]
release v0.20.0 will "bump" rln to "non experimental" aka "ready" https://github.com/waku-org/nwaku/pull/2001 which is a prerequisite for this to be completed. once done we would need:
- [ ] deploy a stable rln contract in testnet (proxy imho)
- [ ] deploy fleets with rln enabled by default

but we still have to decide:
* epoch size. currently 10 seconds. unsure if there is quorum on this.
* if we allow "free traffic".

both points can be discussed at the next research call.

**Comment by jm-clius** [comment]
This epic only tracks decisions around the design parameters. The RLN-in-production work (deploying to fleets, etc.) is tracked in: https://github.com/waku-org/pm/issues/70

Initial requirements would be set once we have merged https://github.com/vacp2p/rfc/pull/616

Realistically, this should be done by 22 Sept, given the upcoming Research Call discussions.

**Comment by jm-clius** [comment]
This issue is closed by the merging of https://github.com/vacp2p/rfc/pull/616
