### ISSUE TITLE
[Epic] 4.4: Open communities on public Waku network

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#78]
**Planned start date**:
**Due date**: 31 Jan 2024

# Summary

  

Once the public Waku network has the following required features, open communities can move from their weakly-protected shared shards to the autoscaling public Waku network:
1. Bandwidth management mechanisms
2. Basic general DoS protection
3. Membership mechanism for Status Communities
4. Distributed Waku services (bootstrapping, Store, etc.)

# Acceptance Criteria

# Tasks

# RAID (Risks, Assumptions, Issues and Dependencies)

**Comment by fryorcraken** [comment]
@chair28980 @jm-clius I am not sure it makes sense to have this epic tracked as this scopes work for the Status team.

**Comment by DeBelg** [comment]
@fryorcraken, does this mean that the whole track 4 disappears?

**Comment by fryorcraken** [comment]
> @fryorcraken, does this mean that the whole track 4 disappears? 
> 

Track 4 is work to be done by Status app team to be able to use the public Waku Network once released.
We documented it for the purpose of communication to Status so they understand what features they would get by using the Waku network and what work would need to be done. It was never part of the Waku work roadmap per se.

**Comment by fryorcraken** [comment]
> @fryorcraken, does this mean that the whole track 4 disappears? 
> 

Actually in the context of the article it may make sense to Include it but Status has not committed to this timeline so it needs to be clear this is Waku's proposal to Status on how they can leverage the Waku Network Gen 0.
